version: "2.3"

services:
  app:
    image: image_api_scalable:v1
    build:
      context: .
      dockerfile: app_docker_file
    container_name: image_api_scalable_container
    runtime: nvidia
    ports:
      - "8000:8000"
    network_mode: "host"

  redis:
    image: redis:latest
    container_name: scalable_image_inference_api_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: